version: '3.7'
services:
  comics-postres:
    image: postgres:12.2-alpine
    container_name: comics_postgres
    environment:
      POSTGRES_USER: comics
      POSTGRES_PASSWORD: comics
    ports:
      - 5433:5432